apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'xxx:25'
      smtp_from: 'xxx@axxx.com'
      smtp_require_tls: false
    route:
      receiver: slack_receiver
    receivers:
    - name: slack_receiver
      slack_configs:
      - send_resolved: true
        username: 'Hardeep'
        api_url: 'https://hooks.slack.com/services/xx/xxx/xxx'
        channel: '#kube-alert'
