kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: demo@devopscube.com
        send_resolved: false
        from: from-email@email.com
        smarthost: email-host-here
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: <slack webhook>
        channel: '#devopscube-demo'

    receivers:
    - name: ipeacocks-alert
      email_configs:
      - to: to-email@example.com
        from: from-email@outlook.com
    # Your smtp server address
        smarthost: smtp-mail.outlook.com:587
        auth_username: from-email@outlook.com
        auth_identity: from-email@outlook.com
        auth_password: y0ur-v3ry-h@rd-p@ssw0rd